language: node_js
node_js:
  - '13'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run build
  - yarn run lint
  - yarn run test
notifications:
  slack:
    rooms:
      - secure: nmlQgWhnKL/C/OOu9WIo3e9uKRT/AJBSpHWjAOBkwZ/XVWBA8a2StkSCrNurR3bK6Z5uXOKRc0mOcQoy/fzNCZ8PXQOXFB8PnqYGmEMCJCTKW7a8vLiSjS7tGU7CWFJqdA+QDzapcoGZHo1ZVNkXdNC52oh/Wt1iOr2u9TQzNOe8Y0YgzRAru55Nvvo0E5VOp3/oUGAMYhIcBPQyl8lpylRylWhLKFYBnlgFz2BNSRwgkwsbiqFpolfpyStzsKMVCNYscPlDMKcNXcQK8aeq4IIfJ38hAXSNV/63d+/2pUdC0HeO9bJtnbocF3HCydGaNUM30zwKgYLbCKI1WbMRRTs4W9EEhRjDS8xJStCabVNUOWMV6UIjm/jtfzfxqqmpAJe/1POz4TfuFD3z+4w8Jdbnrc8XVSjXNFjS6BX95dzaYcKTUkWTzT7mua0gMJC7vKsuEyBceQeJ1FId2Ntlb7+pnOajduhe9B1B+E9rb38Ed0H6DYVOJr1o7ERFMadTT+L7X9s00dAQxofApFjTWCI0bhbRfzm7Q7IHT9EGZ9BWkVQobrTvSo/z4dfCqtUJqA95RZfUMrO1oRW+UYV9L/Mv05sR963+WPZ2JXksgdjWt8LfHmQZwCzMC1Dv7KOdjrPRGjwFRUos9s3yKWhoq/rMgJ4iTaQsfy8yXoFrYBM=
    on_success: never
    on_failure: always
    on_pull_requests: false
