language: node_js
node_js:
  - '13'
install:
  - yarn install --frozen-lockfile
  - yarn run build
script:
  - yarn run lint
  - yarn run test
  - yarn run check
env:
  global:
    - secure: bJq9pj5e3NUFY7KjoIVU4RuopeCBt8QFR/sSExvPWccCV1sTgu0GqXlOMPL8vDduXoKeMkqXHwVzwtjsYfsGIP02+yKfIB4vn9/T+Wq3XOKK1YIgcAJDAJb5PhgzRdCW3uiZs9zQ+IFKiDwgJg0GtaTlyE3OpsHiFgdGaJLXuOORlEPPpqhbLqWSW82kFLsRotPscXbscDGtJ7rTI1OlH7NIWN7JK4/4VPNGzhpMOCnInnU6xrmDWoV8m9xgsjOS2Jl15GKY8QK6SXpf/T0FUNwA2OOxCrV0yg5JC9B5WIfBsHHFFCcuW3QKisXipksK0LtgPxFt8BR3zv1T/1q2PhVn2MqUSg6Dtpqw4XSX24NEk4tLVqnaNLaIV6i9wVTf5f4LxYL8SmlfQRGZ8GULUPBjQEGEtXe9kOGfvF3F+mqQOCvXP+DZ1JXH6ZsfhKL82I+/vkIhBHi9HmHVuXpwTYrb4PYO1IKIbWnXn6Jb4k7fPmGYbFMSq3ABLpuG+Af3pnh0Apnbw2PHf7uTifLMaZ9ssPDKLJA/QnVcR4uyta9FfzfBRcqjl34wiPWo6VsQFQYaU3KCr47bDvykno+8UGDZtUb0taYmbBpPSFHqY4OLkT8wHCG717VIv4qCqU/CBBFVfHJ3z48+SRKqkEErtrxt+kiSX3dxvpq+k1+TcKM=
notifications:
  slack:
    rooms:
      - secure: nmlQgWhnKL/C/OOu9WIo3e9uKRT/AJBSpHWjAOBkwZ/XVWBA8a2StkSCrNurR3bK6Z5uXOKRc0mOcQoy/fzNCZ8PXQOXFB8PnqYGmEMCJCTKW7a8vLiSjS7tGU7CWFJqdA+QDzapcoGZHo1ZVNkXdNC52oh/Wt1iOr2u9TQzNOe8Y0YgzRAru55Nvvo0E5VOp3/oUGAMYhIcBPQyl8lpylRylWhLKFYBnlgFz2BNSRwgkwsbiqFpolfpyStzsKMVCNYscPlDMKcNXcQK8aeq4IIfJ38hAXSNV/63d+/2pUdC0HeO9bJtnbocF3HCydGaNUM30zwKgYLbCKI1WbMRRTs4W9EEhRjDS8xJStCabVNUOWMV6UIjm/jtfzfxqqmpAJe/1POz4TfuFD3z+4w8Jdbnrc8XVSjXNFjS6BX95dzaYcKTUkWTzT7mua0gMJC7vKsuEyBceQeJ1FId2Ntlb7+pnOajduhe9B1B+E9rb38Ed0H6DYVOJr1o7ERFMadTT+L7X9s00dAQxofApFjTWCI0bhbRfzm7Q7IHT9EGZ9BWkVQobrTvSo/z4dfCqtUJqA95RZfUMrO1oRW+UYV9L/Mv05sR963+WPZ2JXksgdjWt8LfHmQZwCzMC1Dv7KOdjrPRGjwFRUos9s3yKWhoq/rMgJ4iTaQsfy8yXoFrYBM=
    on_success: change
    on_failure: always
