language: node_js
node_js:
  - '11'
  - '10'
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn install
  - yarn run build
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run test
after_script: greenkeeper-lockfile-upload
env:
  global:
    - secure: H5MMcevhSWvOF9zHeoLMFigYNiTWLCHvENnCJVc+dN5/fZoaFBBeA9uh4J+5oInp1uyqvIe+q5kCz1NIUCwRpWi/IFjPHLLRkZYIHqPvWyw42xoi4OxWxHjbUzPvzgsFSDI+UUyDXk0kMVmBFyOjFh+G/ORa18dB8I+UmzKEfduhaQ0dSXA7R98Jj8NmUmWJ+3W54C37fR+MiO9GHBf/lGZkvdXZJmHYnAr0xep41KqAdh2BxgcpePoTqDr+iGJ+NejNZULKprGRwvxhBE8qBIzSmT0S50U10bQQ62DAi8HoJ/3WmRIdIDPc3IDnuAkpiPdlyfaboRrxUOaEu67bUJNbiNwwMCa+rpfo3BF3jOD5iCnExYzmX3QzTNR7u1XFmuWNjV2h5b5Rys8k+FYR6FNx/vUrY4279sEex5CRLaYjLGsTlUWg5UkeqL9dbMDigtS4cWh6tAcpK7eLSAg59Z2J9BcsQ8/kf+avtpXkYDJ6bURsgKsc1CRgP5LICM0VR6KXVlzCO9EocXYCGpsD0Ty19FtTnd9YaUsmyFWlnPBspHciGaIarmNDzdURYwfyuDNNUCcwlkJRhSqfVErC8mP7iccEHlpK20/oI6BfXOPiqbVuAsR7Ysrp0/q8A72xMA2CVQ7zIJhfHJlSBAPTDZTN6c1FsxVsX8/udCI1Zoc=
notifications:
  slack:
    rooms:
      - secure: nmlQgWhnKL/C/OOu9WIo3e9uKRT/AJBSpHWjAOBkwZ/XVWBA8a2StkSCrNurR3bK6Z5uXOKRc0mOcQoy/fzNCZ8PXQOXFB8PnqYGmEMCJCTKW7a8vLiSjS7tGU7CWFJqdA+QDzapcoGZHo1ZVNkXdNC52oh/Wt1iOr2u9TQzNOe8Y0YgzRAru55Nvvo0E5VOp3/oUGAMYhIcBPQyl8lpylRylWhLKFYBnlgFz2BNSRwgkwsbiqFpolfpyStzsKMVCNYscPlDMKcNXcQK8aeq4IIfJ38hAXSNV/63d+/2pUdC0HeO9bJtnbocF3HCydGaNUM30zwKgYLbCKI1WbMRRTs4W9EEhRjDS8xJStCabVNUOWMV6UIjm/jtfzfxqqmpAJe/1POz4TfuFD3z+4w8Jdbnrc8XVSjXNFjS6BX95dzaYcKTUkWTzT7mua0gMJC7vKsuEyBceQeJ1FId2Ntlb7+pnOajduhe9B1B+E9rb38Ed0H6DYVOJr1o7ERFMadTT+L7X9s00dAQxofApFjTWCI0bhbRfzm7Q7IHT9EGZ9BWkVQobrTvSo/z4dfCqtUJqA95RZfUMrO1oRW+UYV9L/Mv05sR963+WPZ2JXksgdjWt8LfHmQZwCzMC1Dv7KOdjrPRGjwFRUos9s3yKWhoq/rMgJ4iTaQsfy8yXoFrYBM=
    on_success: change
    on_failure: always
