language: node_js
node_js:
  - '7'
  - '8'
  - '9'
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn install
  - yarn run build
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run test
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: WQKDuibgVR5zwbmrU3fDME6wdb8O8qfsGXAT5h44Yn7T52umVk8MHCWZEa331Ghgk4J1EVTBYVUFuQpE3Jzju7FMaPD8uhLe1oTPUKIjzAQOl9dnxuyYZ60tWoFP6UKni1sHax6AiYWCV5F7ld1ud9kpbMNU2pLcI9Jf5V3RSLRD7nlWGr1ZnP6FYcIOIr/e4xRbHdSNnkQhHxyrUemLl7wH0phZ8vlXoyGkwCf8GwlNKy3QUdgPrrFosVI0O1mH4IiczeeX4kBcNmr1j2r25VI/Mvfo3WO8gKjrtFO7ey/81m57baMNvYBKeRmhmk+g4xLOmnd2EcBSOun/gbI8mUAgiG75vK4KNvB6jgMzoTJlOOtSpchGkfzyfZzVgqZpdwki9HawYqFEc3pGv/UaMCo5FeTsEpZhLKcaPx7SUetbvUp87H6Jthyeqyct/oh0POynbaRxHAlO1ajrC7qR4IN/1/o3JzkBmD5XW4Lc1fOG6ZzV08MWD9dhpTY9VyABrjW4jwoUMaVF6Y4fV0SQ79RKTbT6zDdTh1kCOdT4KILAikrmvTsx1rIzLByhvpsAA4LjygzIMUSWzGpy0MW3g12Upkpf4VPEu2v9w6Vi6/6h/2pudkQVvpN98LwIrpu/3Fp7Jhe0GBUPyy1Ecub2uVog+LMHtJ7r30hPsFxvw6c=
notifications:
  slack:
    secure: MeMFT9uhC2UdzZaEjXiloK/yHRlB2Q5k5/gPbxmJim09v7bzu0dEdusNpWuwbZJY13KXF+pXh1UPa1ICuI/GogQ7+waUldsTE7qCWDxyOAPsZIffPvJLlX4Xnkcod/QaJL1xmb9lgqxMy1jUh0gI3qGmqQ5ZQpWTkQtlnoSoQvJd3FqA1MqVl2WvzUq4ok6rAfM29oX1oVGY3Eo/pvaCms0EyL5HZzYSTYe3mUt1lagT7W2pg9IaEyf1rgHIoReoIsL9RRsu2Luj1XJd4rR1+kR3G3ndmcs5s6XtJK+XpworMEwDjSb1y+gl2FQAhwzqvGW+A7k2u7smENtp9r8qr42T7hVB5hRj4IVnuV3VRG/TLGtQ5YTdMKzV4+IUOfXlZtKKTKxhTG36E1nlSaXs9HQcHwbCguPjYf2wDdDoe5GcaJubStCWVCVgBATg5/A7dUfbTaFfxksVNPNy7yID9n04L8N0kyHljaWOs6VHLnIoTNWRRRitsRBaydwMtIZB6ikijSwqp1WSwKvB8mHCpktB4IWLhhURRtIVY7SP/efHXwIMSM25izOKmRneLIJjiTGxNSAgWvmOTWYAgVEofsXGHEvgQPIqAx177cHv6oWJHS4WpxJACsXarMzwDzHeEbfUPelOc6Vae+zuphtnbsjHfp+pePuZk0w1NEDVJwc=
